-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "private";

-- CreateTable
CREATE TABLE "private"."Installation" (
    "db_id" SERIAL NOT NULL,
    "event_id" TEXT NOT NULL,
    "event_name" TEXT NOT NULL,
    "id" TEXT NOT NULL,
    "account" TEXT NOT NULL,
    "sender" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "db_created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "db_updated_at" TIMESTAMP(3) NOT NULL,
    "db_deleted_at" TIMESTAMP(3),
    "db_deleted" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "Installation_pkey" PRIMARY KEY ("db_id")
);

-- CreateTable
CREATE TABLE "private"."User" (
    "db_id" SERIAL NOT NULL,
    "login" TEXT NOT NULL,
    "id" TEXT NOT NULL,
    "node_id" TEXT NOT NULL,
    "avatar_url" TEXT NOT NULL,
    "gravatar_id" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "html_url" TEXT NOT NULL,
    "following_url" TEXT NOT NULL,
    "followers_url" TEXT NOT NULL,
    "gists_url" TEXT NOT NULL,
    "starred_url" TEXT NOT NULL,
    "subscriptions_url" TEXT NOT NULL,
    "organizations_url" TEXT NOT NULL,
    "repos_url" TEXT NOT NULL,
    "events_url" TEXT NOT NULL,
    "received_events_url" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "site_admin" TEXT NOT NULL,
    "db_created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "db_updated_at" TIMESTAMP(3) NOT NULL,
    "db_deleted_at" TIMESTAMP(3),
    "db_deleted" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "User_pkey" PRIMARY KEY ("db_id")
);

-- CreateTable
CREATE TABLE "private"."Repository" (
    "db_id" SERIAL NOT NULL,
    "id" TEXT NOT NULL,
    "node_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "full_name" TEXT NOT NULL,
    "private" TEXT NOT NULL,
    "owner" TEXT NOT NULL,
    "html_url" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "fork" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "forks_url" TEXT NOT NULL,
    "keys_url" TEXT NOT NULL,
    "collaborators_url" TEXT NOT NULL,
    "teams_url" TEXT NOT NULL,
    "hooks_url" TEXT NOT NULL,
    "issue_events_url" TEXT NOT NULL,
    "events_url" TEXT NOT NULL,
    "assignees_url" TEXT NOT NULL,
    "branches_url" TEXT NOT NULL,
    "tags_url" TEXT NOT NULL,
    "blobs_url" TEXT NOT NULL,
    "git_tags_url" TEXT NOT NULL,
    "git_refs_url" TEXT NOT NULL,
    "trees_url" TEXT NOT NULL,
    "statuses_url" TEXT NOT NULL,
    "languages_url" TEXT NOT NULL,
    "stargazers_url" TEXT NOT NULL,
    "contributors_url" TEXT NOT NULL,
    "subscribers_url" TEXT NOT NULL,
    "subscription_url" TEXT NOT NULL,
    "commits_url" TEXT NOT NULL,
    "git_commits_url" TEXT NOT NULL,
    "comments_url" TEXT NOT NULL,
    "issue_comment_url" TEXT NOT NULL,
    "contents_url" TEXT NOT NULL,
    "compare_url" TEXT NOT NULL,
    "merges_url" TEXT NOT NULL,
    "archive_url" TEXT NOT NULL,
    "downloads_url" TEXT NOT NULL,
    "issues_url" TEXT NOT NULL,
    "pulls_url" TEXT NOT NULL,
    "milestones_url" TEXT NOT NULL,
    "notifications_url" TEXT NOT NULL,
    "labels_url" TEXT NOT NULL,
    "releases_url" TEXT NOT NULL,
    "deployments_url" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "pushed_at" TEXT NOT NULL,
    "git_url" TEXT NOT NULL,
    "ssh_url" TEXT NOT NULL,
    "clone_url" TEXT NOT NULL,
    "svn_url" TEXT NOT NULL,
    "homepage" TEXT NOT NULL,
    "size" TEXT NOT NULL,
    "stargazers_count" TEXT NOT NULL,
    "watchers_count" TEXT NOT NULL,
    "language" TEXT NOT NULL,
    "has_issues" TEXT NOT NULL,
    "has_projects" TEXT NOT NULL,
    "has_downloads" TEXT NOT NULL,
    "has_wiki" TEXT NOT NULL,
    "has_pages" TEXT NOT NULL,
    "forks_count" TEXT NOT NULL,
    "mirror_url" TEXT NOT NULL,
    "archived" TEXT NOT NULL,
    "disabled" TEXT NOT NULL,
    "open_issues_count" TEXT NOT NULL,
    "license" TEXT NOT NULL,
    "forks" TEXT NOT NULL,
    "open_issues" TEXT NOT NULL,
    "watchers" TEXT NOT NULL,
    "default_branch" TEXT NOT NULL,
    "db_created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "db_updated_at" TIMESTAMP(3) NOT NULL,
    "db_deleted_at" TIMESTAMP(3),
    "db_deleted" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "Repository_pkey" PRIMARY KEY ("db_id")
);

-- CreateTable
CREATE TABLE "private"."site_content" (
    "db_id" SERIAL NOT NULL,
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "sha" TEXT NOT NULL,
    "size" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "html_url" TEXT NOT NULL,
    "git_url" TEXT NOT NULL,
    "download_url" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "encoding" TEXT NOT NULL,
    "db_created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "db_updated_at" TIMESTAMP(3) NOT NULL,
    "db_deleted_at" TIMESTAMP(3),
    "db_deleted" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "site_content_pkey" PRIMARY KEY ("db_id")
);
